# Generated by Django 4.0.1 on 2022-01-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('nickname', models.CharField(max_length=45)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('place', models.CharField(blank=True, max_length=45, null=True)),
                ('link', models.CharField(blank=True, max_length=225, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('alarm', models.IntegerField(blank=True, null=True)),
                ('alarm_time', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'post_schedule',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PostSchedule',
        ),
    ]
